apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
      - name: gitops-demo-app
        image: linuxmanl/gitops-demo-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-app
  namespace: demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: gitops-demo-app
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitops-demo-app-tls
  namespace: demo
spec:
  secretName: gitops-demo-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - demo.hostingremote.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-demo-app
  namespace: demo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - demo.hostingremote.com
      secretName: gitops-demo-app-tls
  rules:
    - host: demo.hostingremote.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitops-demo-app
                port:
                  number: 80
